name: Deploy SQL to Azure MySQL

on:
  push:
    paths:
      - 'src/main/resources/schema.sql'
      - 'src/main/resources/data.sql'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Execute schema.sql
        env:
          DB_HOST: ${{ secrets.AZURE_DB_HOST }}
          DB_PORT: ${{ secrets.AZURE_DB_PORT }}
          DB_USER: ${{ secrets.AZURE_DB_USER }}
          DB_PASSWORD: ${{ secrets.AZURE_DB_PASSWORD }}
          DB_NAME: ${{ secrets.AZURE_DB_NAME }}
        run: |
          mysql -h "$DB_HOST" -P "$DB_PORT" -u "$DB_USER" -p"$DB_PASSWORD" "$DB_NAME" < src/main/resources/schema.sql

      - name: Execute data.sql (optional)
        if: hashFiles('src/main/resources/data.sql') != ''
        env:
          DB_HOST: ${{ secrets.AZURE_DB_HOST }}
          DB_PORT: ${{ secrets.AZURE_DB_PORT }}
          DB_USER: ${{ secrets.AZURE_DB_USER }}
          DB_PASSWORD: ${{ secrets.AZURE_DB_PASSWORD }}
          DB_NAME: ${{ secrets.AZURE_DB_NAME }}
        run: |
          mysql -h "$DB_HOST" -P "$DB_PORT" -u "$DB_USER" -p"$DB_PASSWORD" "$DB_NAME" < src/main/resources/data.sql
